remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [TDS Customer Service - Resolve billing issue]
tagline: [Everyting to to know concerning TDS Customer Service - Resolve billing issue]
description: [PLEASE, PLEASE, READ BELOW]

